[package]
name = "tauri-solid-db-template"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib", "lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = [ "specta"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-sql = { version = "2.0.0-beta", features = ["sqlite"] }
tauri-plugin-shell = "2.0.0-beta"
directories = "5.0.1"
include_dir = "0.7.3"

[features]
custom-protocol = ["tauri/custom-protocol"] # This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
